name: Deploy to Spaces

on:
  push:
    branches: [ hfspace ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: hfspace
          lfs: true

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git lfs install

      - name: Push to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git checkout --orphan temp_branch
          git add -A
          git commit -m "Deploy to Space"
          git lfs push --all https://jayllfpt:$HF_TOKEN@huggingface.co/spaces/jayllfpt/table2html temp_branch
          git push -f https://jayllfpt:$HF_TOKEN@huggingface.co/spaces/jayllfpt/table2html temp_branch:main